### ISSUE TITLE
Intro for Collaboration Unit

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization-ambassadors/open-org-workbook#11]
Hello everyone, 
I wrote the proposal for the Intro to Community last week, and below you will find the proposal for the intro to Collaboration. 
Thank you for checking this out and providing feedback! 
Heidi 

--------------------------------------------------------------------------------------------------------

Collaboration introduction

What is collaboration? How does it differ from cooperation or coordination? 
Current definitions of collaboration define it as simple as something as “working together” but it is more complex than that. Other terms also connote “working together”: cooperation connotes working together but with notes of compliance or agreement; coordination defines the act of two or more elements working together effectively (whether they are in agreement or not). They all sound quite similar but they aren’t. 

Collaboration is more than working together with some amount of compliance - in fact, it describes a type of working together that overcomes compliance. And collaboration is more than “working toward a shared goal” -- collaboration is a process which _defines the shared goals via negotiation_ and, when successful, leads to cooperation and coordination.  Collaboration works best when people are transparent -- there is no guessing about what is needed, why,  by whom, or when.  Because collaboration needs negotiation, it implies that collaboration needs diversity (inclusivity)-- after all, if we aren’t negotiating among differing views, needs, or goals, then what are we negotiating? The act of authentic and purposeful collaborating directly necessitates the emergence of transparency, diversity, discussion, and negotiation -- it assembles part of the collective purpose spontaneously. 

Open Organizations
In traditional organizations, there is an agreed-upon set of goals that people are welcome to support, or not (leading to decreased morale, job satisfaction, performance, etc).In these organizations, there is some amount of discourse and negotiation but, at best, a higher-ranking or more powerful member of the organization intervenes to make a decision which the membership must accept, or at worst it is ignored. With Open Organizations, however, the focus is for members to perform their activity and to work out their differences; only if necessary would someone get involved (and even then would try to do it in the most minimal way that support the shared values of community, transparentcy, adaptability, collaboration and inclusivity. This make the collaborative processes in open organizations “messier” (or chaotic to use Whitehurst’s term) but more participatory and, hopefully, innovative. 

[Thoughts on the section's case studies can go here.]

In Open Organizations we can see how collaboration is communal -- it needs Inclusivity and transparency to propel its negotiation toward merit-based activity rather than on activity defined by members with high social status or power.

**Comment by semioticrobotic** [comment]
I really like this  approach, @HeidiHVL. Your decision to distinguish carefully between "collaboration," "cooperation," and "coordination" will make the piece quite strong, and I'd suggest sticking with that!

**Comment by HeidiHVL** [comment]
Thanks @semioticrobotic !
