### ISSUE TITLE
Case study: Facilitating "Inner-Sourcing" in Red Hat IT

### ISSUE THREAD

**Issue by tombenninger** [open-organization-ambassadors/open-org-workbook#13]
I'd like to see/write some content on Inner-sourcing (treating IT work as an open source projects, referenced lightly in at least one earlier open org books) which could possibly be set up as an exercise or a possibly a case study.

 * A brief overview of inner-sourcing.
 * Best practices for inner-sourcing.
   * Understanding all stakeholders (service owners, operations, other users, finance, etc.)
   * Understanding principles and requirements
   * Identifying decision makers
   * Ask and discuss before merge request
 * Example process for inner-sourcing changes to IT services. (Basically maintaining awareness of service + continual ODF work)
   * Change cadence
   * Change capacity
   * Merge requests and peer review

**Comment by semioticrobotic** [comment]
This is great, @tombenninger, and a useful addition to the book. I _think_ it would work best as a case study, but the details that would help me determine that for sure are missing from your description. What/which organization forms the basis of your case study? What is the inner-sourcing effort like there? How long as it been going on? I'm assuming your outline of potential best practices (above) is the result of experience; we just need to be sure we get that into the writing, too!

**Comment by tombenninger** [comment]
I work within Red Hat IT, and the specific case I'd like to review is the interactions between across 3 teams to improve internal tools.

The team who 'owned' the tools continually had higher priorities for several months, leaving their tool users in a painful situation. We struck and agreement to open up the tool development, and saw great leaps forward in usability, and then continued development in this model to extend the tools.

This model is now being used for other tool development efforts, and is something we're starting actively promote now.

**Comment by semioticrobotic** [comment]
Thanks for that, @tombenninger. I appreciate the additional context. I'll go ahead and add you to the working table of contents! In the meantime, as you draft, please don't hesitate to reach out. Thanks!

**Comment by ShaneCurcuru** [comment]
"Inner Source" is still a new term but it's definitely got some good information and advocates behind it that are closely allied to The Open Org ideas, so some treatment - even if just an acknowledgement and description - would be very valuable.  The case study is a good way to add it, but just having the connection between open ideas here and the inner source term is a good addition.

**Comment by tombenninger** [comment]
@ShaneCurcuru It seems like a good match, and I have (hopefully)) some good examples of it in Red Hat IT. I did find [sources goes back to 2000](http://www.inner-sourcing.com/wiki/inner-source-wiki/) but this actually leads me to an issue that [newer sources](http://paypal.github.io/InnerSourceCommons/) are calling it "InnerSource" to make it more searchable, but this isn't consistent. I've seen "Inner Source", "Inner-Source", and "InnerSource" all used, sometimes on the same site. 

I also did not anticipate how long it would take to dig through 4 years of emails, git commits, and other documentation, but work is progressing, and I should push my first draft in the next day or two.

**Comment by semioticrobotic** [comment]
(Sent via email, too.)

Thank you for this case study, @tombenninger. It's exceptional and really speaks to the book's themes and vision.

I've made some line edits and offered a few questions/comments for you in the margins. I also left a note at the end for you (asking for a conclusion that's a bit more robust). All in all, though, this is moving in a productive direction. Please take a look when you have a moment and let me know what you think.
