### ISSUE TITLE
Example framework and exercise scaffolding

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization-ambassadors/open-org-workbook#15]
I've create a document that includes a bit of writing about pedagogy and the exercises for the front matter and an example agenda for the Inclusivity Unit. It contains a framework, but also three sample exercises. The third is half-baked. 

At 10 pages and writing about how diverse perspectives lead to more sustainable and effective project, I don't feel like I should write another word without insight and feedback ;)

https://docs.google.com/document/d/1sphQW6op50NSPDjMKs5Ien3cP3M0aNsqquVrzsAVf0k/edit#

**Comment by semioticrobotic** [comment]
I'm diving into this and loving it! Thanks, @LauraHilliger.

**Comment by LauraHilliger** [comment]
@semioticrobotic you said others are contributing exercises? Want to point me towards them? Maybe I can help remix/reformat to fit this frame?

**Comment by semioticrobotic** [comment]
Absolutely, @LauraHilliger! I am editing a batch right now. We're publishing a great example from @samuelknuth on Thursday at Opensource.com. I'll also be pushing a new set of book galley proofs very soon.
