### ISSUE TITLE
Case Study: Growth of OpenStreetMap

### ISSUE THREAD

**Issue by wonderchook** [open-organization-ambassadors/open-org-workbook#16]
@heatherleson and I propose to write the following case study: 

# Summary

OpenStreetMap began in 2004 as a small group of people and essentially a hobby. Since that time it has grown into a large global community. This growth has not been without challenges in working towards creating an inclusive community. We propose that this case study will review the growth of the OpenStreetMap community and the challenges of an open collaboration to create a free map for the entire world. 

# Our thesis
HOT and Missing Maps is changing the community. It is helping it become more global and inclusive. It is forcing the traditional OSM to evolve. This creates the friction to grow faster with the influx of learning and growing joys. The principles of open collaboration are not changing at their core with this shift, the methods and ways they are applied however are adapting. How can a community make space and be welcoming to big growth shifts in organizational change. In the case study we will review the following:

* Stakeholders: businesses, humanitarians, volunteers, technologists
* Changes in governance of the project
* Initiatives to make the technology around OpenStreetMap easier for those from different backgrounds to use
* Regional differences in community collaboration

**Comment by semioticrobotic** [comment]
This is lovely, @wonderchook and @heatherleson. Very much looking forward to working with you on this.

In which of the book's units do you see this case study fitting most appropriately?

**Comment by wonderchook** [comment]
Sorry we missed this, looks like you slotted us into community which makes perfect sense.
