### ISSUE TITLE
New section: How brands affect communities

### ISSUE THREAD

**Issue by ShaneCurcuru** [open-organization-ambassadors/open-org-workbook#17]
One major topic that's not directly covered anywhere is the effect of brands on how open organizations work, especially in terms of governance (who makes final decisions) and community membership (who can actually use the trademarks in their work directly, for the community outside the legal company).

I know this is an important topic, but I'm not sure how best it fits in the writing structure you've currently got, so I'm hoping someone can help focus it.  Separately, there are a lot of issues around management of trademarks which are important, but out of scope here (and the ecosystem isn't ready yet to internalize how that works yet - there's still work on the basics to do like these books!)

Branding and marketing can certainly touch on all the definition points, but it's most applicable to Inclusivity and Community.  Since the brand is both the physical symbols the organization uses to portray itself, as well as the _perception_ of those symbols in the eyes of the rest of the world, it can subtly change how people outside a core company interact.

Traditional brand symbols affect Inclusivity by defining the organization's environment - is it welcoming to outside community participation?  Is the brand architected so that newcomers feel welcome, and feel like they have some place within the brand and the work, or not?

Branding especially matters to community, when part of that community is not employees.  Who defines what the product is? Can community members use product brands as part of their work extending your work? Does the brand have tie-in but separation like RHEL/Fedora? In particular, **who** gets to decide exactly what the brand means and where it can be used - and how is that strategy (which is different than technical or operational strategy work!) communicated clearly throughout the community?

**Comment by semioticrobotic** [comment]
This is a timely and important topic, @ShaneCurcuru. Thanks for submitting this. Be sure to check out recent articles from [Chris Grams](https://opensource.com/users/cgrams) and [Chad Whitacre](https://opensource.com/users/whit537) for a little background on his this conversation has been unfolding on Opensource.com specifically.

The issues and questions you pose here are great. For this book project specifically, we're especially interested in tracking down case studies—stories from organizations practicing openness at scale. So if you have a story (perhaps from Apache?) about how these issues played out, in practice, and had concrete consequences for the way(s) the organization worked, then we'd love to have _that_ chapter. I think it'd fit the Community section of the book very well.

Thoughts or ideas?

**Comment by pdurbin** [comment]
Would the Hudson/Jenkins story be a good one to write about?

**Comment by HeidiHVL** [comment]
Hi @ShaneCurcuru that's an interesting point. I'm writing the intro for the Community section. I'll see how I might work it in to the intro as an influence on open communities. I think they exist on a continuum of the values that the books calls out -- for instance, meritocracy exists on a scale from 0 to 10 in any community. (Zero being not at all open! Ten being truly the most open meritocratic community ever.) So Brand strategy would define/influence how meritocratic a community created by an organization could be. 
The influences that impact a community are infinite... but I think the awareness that your idea about brand would bring is really helpful to readers of the book. 
Thank you for submitting it. 
Best wishes,
Heidi
