### ISSUE TITLE
Exercise: Bias Checklist

### ISSUE THREAD

**Issue by yevster** [open-organization-ambassadors/open-org-workbook#19]
(Please assign to me - I don't seem to have permissions)

**Comment by yevster** [comment]
Here is the first draft. I'd love to get some comments! (Will probably need to replace hyperlinks with footnotes for the printed version)

# Exercise: The Bias Checklist

**Estimated time to complete:** 15 minutes first time, 2-5 minutes subsequently.

**Materials necessary:** Editable copy of this text, or print-out and a writing implement

**Exercise type:** Checklist

Bias is the single greatest threat to the open organization. This is no exaggeration. In traditional organizations, responsibilities for evaluating ideas, strategies, contributions—even people—typically fall on (presumably) trained managers. In _open_ organizations, that responsibility rests with contributors of all sorts.

"In organizations that are fit for the future," writes Jim Whitehurst in _The Open Organization_, "Leaders will be chosen by the led. Contribution will matter more than credentials [...] Compensation will be set by peers, not bosses." According to Whitehurst, an open organization is a meritocracy: "Those people who have earned their peers' respect over time drive decisions." But the way humans allocate their respect is itself prone to bias. And imagine what can happen when biased decision-making results in the wrong leaders being chosen, certain contributions being over- or undervalued, or compensation being allocated on something other than merit.

The following checklist covers several documented phenomena that, sometimes unconsciously, skew the decision-making practices.

## The bias checklist
☐ **Has this person done a favor for you?** If so, you are more likely to impulsively do something that feels like a favor to them. This principle of reciprocity is very powerful. This is why when charities send you solicitations by mail, they will often include address labels, calendars, other cheap goodies. When you feel like you've been given something, you are more likely to find yourself giving something back. Reciprocity is especially dangerous in an open organization, where the odds of two contributors having to evaluate each other's contributions are drastically higher than they may be elsewhere. [(Positive Reciprocity)](https://en.wikipedia.org/wiki/Reciprocity_(social_psychology))

☐ **Has this person done something unfavorable to you?** Reciprocity works both ways. Even if you can swear up and down that you're not the type who bears a grudge, if someone has previously rejected contributions from you, be especially alert for the desire to reject a contribution from them. [(Negative Reciprocity)](https://en.wikipedia.org/wiki/Reciprocity_(social_psychology)).

☐ **Has someone else done something particularly favorable or unfavorable to you?** While we're on the subject, be on the lookout for Generalized Reciprocity - a tendency to "pay it forward", or to "do onto others" what someone else has done to you. There has been [evidence](http://psycnet.apa.org/doiLanding?doi=10.1037%2Fa0031047) of a higher tendency to pass on negative or unfair behaviors than positive ones, so if you feel "wronged" at the moment you're evaluating a contribution, this feeling can influence your evaluation. [One study](https://www.nature.com/articles/srep22316) found writing a message to the original perpetrator of an unfair or unjust behavior explaining your feelings can reduce your impulse to pass that unfairness onto others.

☐ **Have you already done something nice (however small) for this person?** This one's a bit more subtle than reciprocity, but no less powerful. Subscribe to the mailing list of a major political party, and you will be inundated with requests to fill out a survey or make a small donation (e.g. $1). These are effective solicitation techniques, because once you have done something positive for someone, you become more likely to do something even bigger for that person. This phenomenon is sometimes called the "[Foot In The Door](https://en.wikipedia.org/wiki/Foot-in-the-door_technique)" technique. If you have spoken favorably of an idea, a contribution or a contributor, or approved past work of the contributor, you will be likely biased in favor of that contributor.

☐ **Have you previously spoken ill of an idea, a contribution, or a person?** The same need for consistency with oneself that powers the Foot in the Door technique also works in the negative. If you have previously treated an idea, a contribution, or a person with disdain or have otherwise acted unfavorably toward a person, you will be predisposed to continue to act in that way.

☐ **Is the person good looking?** It has long-since been [documented](http://psycnet.apa.org/record/1974-25236-001) that the attractiveness of someone performing a task influences our evaluation of how someone performs that task. This is an example of the [Halo Effect](https://en.wikipedia.org/wiki/Halo_effect) - a phenomenon whereby one attribute of a person leads us to assume or overestimate other attributes of that person.

☐ **Is the person successful or renowned in unrelated areas?** This is another example of the halo effect. For example, [Stephen Hawking's anti-AI pronouncements](http://www.bbc.com/news/technology-30290540) received wide press coverage across the world, even though all of Stephen Hawking's education and accomplishments are in physics and cosmology. Another example comes direct from the original *The Open Organization*. Mr. Whitehurst writes about how Gavin King (creator of the [Hibernate](https://en.wikipedia.org/wiki/Hibernate_(framework)) Framework) was allowed to embark on a new project to create a new language for the JVM. Today, that language, [Ceylon](https://ceylon-lang.org/), languishes in relative obscurity, compared to competing JVM languages [Scala](https://www.scala-lang.org/) (which has existed for years prior to Ceylon) and [Kotlin](https://kotlinlang.org/) (released at about the same time). Data frameworks and programming languages are examples of substantially different areas, so it seems fallacious, in retrospect, to assume resounding success in one area would portend any success in the other.

☐ **Does a person or a contribution have similarities to someone or something you respect or admire, or dislike or oppose?** When making evaluations, we have a tendency to compare what we see to similar things from our own experience and pass judgment based on similarity to those things. This is why, for example, political activists often like to compare the people they oppose to Hitler. None of those being compared have objectively committed wrongs even remotely resembling Hitler's mass murders, but the comparisons are driven by the intuition that any similarity to Hitler presents the target in a negative light. [(Similarity Heuristic)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1030517) 

☐ **Does this person meet or violate your norms for how a successful person in a looks?** Whether or not we admit it to ourselves, we all have biases and stereotypes for what a successful person in a field looks like. For example, when asked to picture a successful software engineer, many of us will think of a white or Asian male. While gender and racial biases have been widely discussed, awareness of them alone is not to compensate for their effect. We have to make these unconscious biases conscious and force ourselves to second-guess our judgments in their light.

## Avoiding biases
Knowing about a bias may not be enough to prevent its effects. Many of us just aren't that good at correcting ourselves. This is why it's crucial to take steps wherever possible to avoid biases:

☐ Evaluate contributions anonymously. Orchestras, for example, will often audition musicians without seeing them. This practice has [reduced the gender gap in major orchestras](https://www.theguardian.com/women-in-leadership/2013/oct/14/blind-auditions-orchestras-gender-bias) long before it became adopted by televised talent shows.

☐ Define structured and rigorous evaluation criteria for people and contributions.

## Opening up on biases
Knowing about, and even anticipating, our biases is the first step in the journey to overcome them. But it is not the end.

Working through the checklist above, for instance, one may be attempted to acknowledge the _possibility_ of the biases—but ultimately deny experiencing them. Bad news: This may itself be a bias talking. Humans have been found to be overconfident in their abilities in virtually all areas, from [driving](http://www.sciencedirect.com/science/article/pii/0001691881900056?via%3Dihub) to [investing](https://www.cbsnews.com/news/how-overconfidence-hurts-investors/). So there's every reason to assume we may be overconfident in our own ability to screen ourselves for biases.

Fortunately, the structure of the open organization can help us overcome overconfidence. In _The Open Organization_, Jim Whitehurst writes about the principle of _360-degree of accountability_, meaning "you are accountable to everybody." 360-degree accountability empowers participants to recognize biases not only in themselves (which is difficult to do) but also in others (which is easier). "My job is [. . .] to take questions and feedback and engage associates in a conversation about the decisions we're making as a team," Whiterhurst writes. Thus, in an open organization, it should be appropriate—indeed, encouraged—to ask, for example, "have you thought you might be biased in favor of _X_ due to your prior positive statements about it?" The answer to the question, rather than a "yes" or "no," should be the concrete steps one has taken (or will take) to avoid bias. A reasonable response may be: "No, I haven't thought of it, but now that you mention it, let me ask Y, who has not dealt with X previously, for a neutral perspective."

When bias is acknowledged, discussed, and counteracted proactively and systematically, an organization becomes more deeply empowered to scale trust, responsibility, and accountability across the organization. An open organization relies on the soundness of human judgment across its ranks. Taking every possible step to make this judgment as objective and trustworthy as it can be is therefore absolutely imperative.

**Comment by semioticrobotic** [comment]
This looks like a great start, @yevster. Thanks for taking this on.

Do you have plans for any kind of "evaluative" or "summary" part of the exercise? Something at the end that helps participants review and/or reflect on the results? Maybe a "scale" or "scorecard" that helps make sense of the findings? (For example: "If you checked fewer than three boxes, then..." or "If you checked more than 4 boxes, then...")

**Comment by semioticrobotic** [comment]
Oh, and yes: We _will_ convert your documentation (thank for that!) to footnotes in the printed version, but that's further down the road and the links are much more preferable here.

**Comment by semioticrobotic** [comment]
**Update:** I made a few edits to the introduction, @yevster. See what you think.

**Comment by yevster** [comment]
Made a few edits (most trivial, changed the "norms" to be more skin-deep, as stereotypes usually are). I don't want to give a scorecard, because nobody who checks only one box is exempt from having to compensate for that bias. Also, there is no literature that I'm aware of (which isn't saying much) that rates one bias/heuristic against others.

**Comment by yevster** [comment]
I will add a summary or concluding paragraph.

**Comment by semioticrobotic** [comment]
Makes sense to me, @yevster. Thanks for your work on this. Let me know when you'd like me to make another pass through it.

**Comment by semioticrobotic** [comment]
How is this going, @yevster?

**Comment by yevster** [comment]
Will have a go at it this weekend. Sorry for the delay

**Comment by yevster** [comment]
@semioticrobotic, added a concluding section. Please have a look. Thanks!

**Comment by semioticrobotic** [comment]
Just reviewed and made a few small tweaks, @yevster. I really like it. How do you feel about the current state of the draft? Want to get it into typesetting soon?

**Comment by semioticrobotic** [comment]
Update to the above: If in the next few days we're able to get this to a place that comfortable for you, then there's a good probability we could run it on Opensource.com as an advance "preview" chapter from the book (to aid promotion). No pressure, @yevster—but if that seems possible let's discuss!

**Comment by yevster** [comment]
Thanks for all the grammar fixes (not my strong suit)! Made a couple of tiny wording changes, and at this point, I'm happy with it. I'm happy posting it on opensource.com, as long as the hyperlinks/citations make it too.

**Comment by semioticrobotic** [comment]
The excellent and extensive citations will indeed make the jump. Thanks, @yevster!

**Comment by semioticrobotic** [comment]
Do you have an account at Opensource.com, @yevster? If so, what user name is associated with it?

**Comment by yevster** [comment]
I do have an account, @semioticrobotic. And, quite surprisingly, it’s “yevster”. 😀

**Comment by semioticrobotic** [comment]
Take a look at [this link](https://opensource.com/open-organization/17/10/open-decision-bias-checklist), @yevster. That's a pre-publication proof of your article for your review (make sure you're logged into Opensource.com).

Note that the headline and subhead are still in flux as our editorial team works to make them most effective. If you have suggestions here, please do send them along.

**Comment by yevster** [comment]
Looks good. Not sure if the gavel is the optimal graphic. How about this one?http://maxpixel.freegreatpicture.com/Checklist-Man-People-Box-Hand-Goals-Pen-Notebook-2589418

**Comment by semioticrobotic** [comment]
Thanks for the feedback, @yevster! I will change the lead image per your request.

**Comment by semioticrobotic** [comment]
Hope you saw that [the article went live](https://opensource.com/open-organization/17/10/open-decision-bias-checklist) today. Great work, @yevster!

**Comment by yevster** [comment]
Thanks, Bryan! Looks great!
