### ISSUE TITLE
How to submit text?

### ISSUE THREAD

**Issue by tombenninger** [open-organization-ambassadors/open-org-workbook#20]
@semioticrobotic This may seem like a strange question, but what is the best way to submit the text? With this project being in GitHub, I sort of assumed we would be checking in content, but I don't see branches or pull requests... is email the best path forward, or something else?

**Comment by semioticrobotic** [comment]
Not a strange question at all, @tombenninger! I'm glad you opened this issue so we can clarify.

The short answer is that I can work with authors in whatever way is best for them. Many have been sharing collaborative documents with me (i.e., GDocs and the like), while others have been emailing me LibreOffice Writer and/or markdown files. If you'd like to use GitHub, then I can accommodate that, too!

Whatever works for you works for me.
