### ISSUE TITLE
Proofread the entire manuscript

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-workbook#27]

**Comment by jhibbets** [comment]
Page 15 - 2nd para "Senior" the word senior seems weird here to me. "Senior people aren't the only ones interested in working openly." Reading the first para and going from to that seems like it needs a better transition. Who are senior people?
@semioticrobotic

**Comment by jhibbets** [comment]
Page 17 - missing bio for Jim
@semioticrobotic

**Comment by jhibbets** [comment]
page 23 first full para - does self-reflection need to be hyphenated?
@semioticrobotic @samuelknuth

**Comment by jhibbets** [comment]
page 25 - 4th full para, last sentence 
The same is true of changing the ways we think.
or
The same is true of changing the way we think.

way vs ways??
@semioticrobotic  @samuelknuth

**Comment by jhibbets** [comment]
page 29 5th bullet has an extra space between experience and the "
experience.  " --> experience. "
@semioticrobotic

**Comment by jhibbets** [comment]
page 32 - second full para - I might expand IRI after the 16 footnote to dragonfli. If there are only two occurrences, it might help the reader. Since this was a new term for me, I had to stop and go back up to the see what is was again.
@semioticrobotic @jenkelchner

**Comment by semioticrobotic** [comment]
Got 'em. Thanks. In Jim's piece, "senior people" refers to folks higher up the corporate ladder (your C-Suite, etc.).

**Comment by jhibbets** [comment]
I have proofed all units and added comments / fixes in the main proofreading issue: https://github.com/open-organization-ambassadors/open-org-workbook/issues/25
