### ISSUE TITLE
Need review and discussion questions for transparency case study

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-workbook#28]
On page 61 on the proofs (in Unit 1: Transparency), review and discussion questions are needed for the chapter "Dismantling departmental silos through chat transparency."

You can see others chapters for examples. Each chapter has three review and discussion questions.

**Comment by semioticrobotic** [comment]
The author submitted final changes today, so I'll write the questions in order to firmly put this one to bed.

**Comment by semioticrobotic** [comment]
- The phrase "default to open" became exceedingly important to Guy's organization. What does it mean to you? How would "defaulting to open" impact your team or organization? Would it make  you reconsider your approach to transparency and sharing?

- To solve his organization's chat platform problem, Guy says he turned to "a philosophy I'd formed through challenging experiences in my career: 'Culture first, tools last.'" What does this philosophy mean to you? In what ways does it represent a shift form traditional organizational practices? What would be its impact if you and your team adopted it? And how would it cause you to think differently about your team's level of comfort with transparency?

- Embracing transparency allowed Autodesk to locate and foster volunteering champions of the organization's chat platform. How might working more transparently help you locate talent and innovative potential currently hidden within your organization?
