### ISSUE TITLE
Publish an EPub Version?

### ISSUE THREAD

**Issue by cwawak** [open-organization-ambassadors/open-org-workbook#34]
Hi - I'd like to read this doc on an e-reader, and the PDF format renders poorly on those. I've tried converting the ODT file using Calibre, and I've gotten less than excellent results - tables are misrendered, TOC doesn't work, and so on. Is it possible to officially publish an EPub version?

**Comment by semioticrobotic** [comment]
Thanks, @cwawak, for checking in. You're correct that producing reliable ePub versions have been difficult—for all the reasons you've already experienced! Some folks in the community (myself included) have had some luck using [Writer2epub](https://en.wikipedia.org/wiki/Writer2epub) for the job. We're always happy to review pull requests for ePub versions!

**Comment by cwawak** [comment]
I messed around a little more, and #35 seems the best output so far.

**Comment by cwawak** [comment]
I messed around a bit, and found that ODT -> XHTML -> Calibre -> EPUB seemed to work well, resulting in #35. Happy to make tweaks to better reflect the correct metadata.

**Comment by semioticrobotic** [comment]
Note that this is resolved with [commit 9d1bfce](https://github.com/open-organization-ambassadors/open-org-workbook/commit/9d1bfce1fd9e73d6fed737928494e1767308db9b).
