### ISSUE TITLE
Cross-org Collaboration that works

### ISSUE THREAD

**Issue by seamurphredhat** [open-organization-ambassadors/open-org-workbook#4]
The thinking here is a chapter (or perhaps its only a section of an existing chapter initially (?)) that builds on many of the operating principles outlined in the book and from there outlines a model for cross-BU / cross-eng team program collaboration (from strategic alignment planning (and influence), PM team POR planning, software production, delivery, consumption).

Not that we (RHT) have it all figured out yet (ack we're not in a position today to get all preachy about it, with loads of precision around the 'how's' ;-) but we have some examples where we have delivered integrated solutions already, and a set of fwd-looking smart people considering the mechanics / systems / processes, as well as the various org dynamics aspects.

--
Sean Murphy

**Comment by semioticrobotic** [comment]
Thanks for this, @seamurphredhat! I'd love to hear more about this. At the moment, I'm just having a bit of trouble extracting some essentials from this description. Can you help me understand:

- What is the nature of the specific case study in this description? I understand the organization is Red Hat, but what was the specific project/initiative you or your team undertook?
- What was the challenge this undertaking was meant to solve or address? What prompted it, in other words?
- What were the results of the initiative?
- Which section of the book do you see this figuring into (as per the table of contents)?

Apologies for the extra work. I just want to be sure that I understand the scope of the pitch.
