### ISSUE TITLE
The Dataverse Project at IQSS at Harvard as a case study

### ISSUE THREAD

**Issue by pdurbin** [open-organization-ambassadors/open-org-workbook#6]
I just mentioned the idea of including @IQSS as a case study here: https://groups.google.com/d/msg/dataverse-dev/hCoMDMinbd8/6C_qTdfiBAAJ

We have open roadmaps, at least: https://www.iq.harvard.edu/roadmaps

I heard about this project at the "New open organization book project" post at https://groups.google.com/d/msg/todogroup/NDx6PvMzWl4/ah6ZBXPhCAAJ

**Comment by semioticrobotic** [comment]
This is perfect, @pdurbin. We'd love to feature @IQSS as a case study. If you are committed to working on this with us, I'll go head and add your data to the working documentation. Then we can be in touch about the best approach for your case study in transparency. Thanks so much.

**Comment by pdurbin** [comment]
@semioticrobotic I discussed this with @djbrooke and I just changed the title of this issue to indicate that if we decide to contribute a case study, we would prefer to narrow the scope from all of IQSS to just the Dataverse project. We would still mention other related projects at IQSS, of course.

The biggest question we have is how much effort is expected from us. Can you link us to existing case studies or give us a sense of approximately how many words are expected? Is just text ok or are you expecting lots of images? Thanks!

**Comment by semioticrobotic** [comment]
Thanks, @pdurbin. Happy to take whatever direction is best for you.

Here a few additional details that may help guide your thinking around the chapter:

- Case studies won't need to be inordinately long—perhaps anywhere from 800–1200 words; we're flexible.
- Case studies are largely narrative descriptions. We can work with an image or two (we prefer to do this in the case of diagrams or other instances in which the image is directly relevant to the narrative or a specific referent for the text).
- Specific requirements for the case studies are [available in this repository](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_org_list.md#framework-for-case-studies). We are currently working with a few writers to get some already well-developed case studies into production so others can reference them as potential examples for their own work.
- I can work with you every step of the way to bring the story to life: help you brainstorm, review an outline, jump right into draft editing with you—whatever you need

Does that help?

I'll go ahead and update our records to reflect the new focus of your chapter.

**Comment by pdurbin** [comment]
@semioticrobotic yes, this helps. Thanks. I think my biggest concern is the timeline posted at https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/README.md#project-timeline which says:

August 8—Project announcement  
August 25—Table of contents freeze  
October 6—Content freeze  
November 10—Editing freeze (final freeze)  
November 27—Soft launch  
December 4—Formal launch

This strikes me as somewhat aggressive, but I guess it gives me all of September to come up with something. The timing isn't great for me because I have a talk to write on top of my normal day job. Ideally, I would first read the [The Open Organization: Igniting Passion and Performance](https://www.amazon.com/Open-Organization-Igniting-Passion-Performance/dp/1625275277) book by Jim Whitehurst but I can probably only realistically commit to reading the [The Open Organization Definition](https://opensource.com/open-organization/resources/open-org-definition) before putting pen to paper.

The requirements you linked to seem to be focused on organizations, which makes complete sense, but again, anything I write would be more focused on the project I work on within the organization. Here are the requirements so I can see them all in one place:

Each **case study** should include specific organizational data such as:

- Company name
- Number of employees
- Description of company (products/goals/mission)
- Identification of "open" principles at work (e.g. Does the organization use the language of open source in some way? Where do we think they fall on the Maturity Model)

Each case study should answer (at minimum) the following questions:

- What was the **problem** the organization was facing?
- What **solution**, based on principles from the [Open Organization Definition](https://opensource.com/open-organization/resources/open-org-definition), did it implement to solve this problem?
- What was the **outcome** of this work?

I don't mind that you added me to your table of contents for now but I don't want to get your hopes up that I'll actually complete a suitable case study on time. I do appreciate that you're so willing to help and interested in our story. At the very least, my goal would be to educate myself on the open organization concept and I try to knock something together. Thanks!

Oh, I just noticed that at https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_toc.md you wrote, "Case study: Harvard University Dataverse project (transparent data for better research)—Philip Durbin" and I don't object at all to being in the transparency chapter but I wouldn't be writing about transparent data. I'm not even sure what that is. 😄 The default license for Dataverse is CC0 but I'd be writing more about transparency in our process of software development by way of:

- public roadmap
- public kanban board for dev issues
- public kanban board for design
- public issue tracker allowing public comments (GitHub issues)
- public mailing list with open archives
- public chat room with public channel logs
- public bi-weekly community calls
- public (and free) annual community meeting
- other stuff I'm forgetting 😄 

Does this sound like the kind of content you're looking for? Can you put my in a time machine so I can go read the Open Organization book? 😄

**Comment by semioticrobotic** [comment]
Thanks for this detail and context, @pdurbin. Just so I'm sure to address all dimensions of your note, let me break it up a bit here.

> This [timeline] strikes me as somewhat aggressive, but I guess it gives me all of September to come up with something. 

Yes, it's December or bust. But I'm confident that everyone working together can meet that goal. The October 6 content freeze is the date by which all complete (however rough) drafts should be into editing. For a few weeks after that we'll continue to work on the piece in order to polish it. Early submissions are always welcome—but we understand the hard limits of time.

> Ideally, I would first read the _The Open Organization: Igniting Passion and Performance_ book by Jim Whitehurst but I can probably only realistically commit to reading the _The Open Organization Definition_ before putting pen to paper.

If time permits reading only one, then you've picked the right one. Jim published his book in 2015, but it did not contain the comprehensive definition. The latter is a community project aimed at extending the theoretical and practical purchase of the book, and now it's guiding the new volume. Reading that will give you a great start.

> The requirements you linked to seem to be focused on organizations, which makes complete sense, but again, anything I write would be more focused on the project I work on within the organization.

Of course! And a project is an organization, is it not? A group of people assembled around a common problem, working together toward some goal? Our community is always quick to assure people that "organization" need not mean "for-profit firm" or even something like "university." The primary goal is to understand how open principles can affect the way(s) people _organize_ in pursuit of something. Your project certainly seems to fit that description.

> I don't mind that you added me to your table of contents for now but I don't want to get your hopes up that I'll actually complete a suitable case study on time. I do appreciate that you're so willing to help and interested in our story.

Yes; always willing to help. We're very interested in the story and want to see it come to fruition! Lean on us when you need to; it's why we're here.

>  I don't object at all to being in the transparency chapter but I wouldn't be writing about transparent data.

Gotcha. Noted. Your proposed bullet points are perfectly fine, of course, and they'll take an even more effective shape (for you, for readers) when they begin to cohere around that narrative arc that you've identified above:

- What was the problem the organization was facing?
- What solution, based on principles from the Open Organization Definition, did it implement to solve this problem?
- What was the outcome of this work?

**Comment by semioticrobotic** [comment]
On Friday we crossed our [first milestone](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/README.md), @pdurbin. So we're now moving onto the writing stage of the project.

As we discussed above, please feel free to drop me a line (here, email—whatever works) with your questions, comments, and concerns as you go along. You can also send a note to <bbehrens@redhat.com> if you'd like me to add you to the author email list.

Happy writing!

**Comment by pdurbin** [comment]
@semioticrobotic my only concern is that we make it clear that I just happen to work at Harvard.

**Comment by semioticrobotic** [comment]
Roger that, @pdurbin. Can do. Hope your writing is going well. Let me know if I can help in any way.

**Comment by pdurbin** [comment]
@semioticrobotic @djbrooke @mercecrosas ok, this morning I banged out "Transparency in the Dataverse Project", weighing in at 992 words, smack in the middle of the 800-1200 words you asked for. I'm sure there's stuff I'll tweak in there but I enabled public comments and I'm eager for feedback: https://docs.google.com/document/d/1ZbkHtHe19xadLFZoWnVxbS0XFzau2OGbDGwGaKGYqfE/edit?usp=sharing

Thanks!

**Comment by pdurbin** [comment]
> The timing isn't great for me because I have a talk to write on top of my normal day job.

Oh, I should also mention that the talk I'm giving is related and I'm planning on mentioning this case study and The Open Organization Workbook. Some info on my talk: http://wiki.greptilian.com/talks/2017/javaone-how-to-run-an-open-source-project

**Comment by semioticrobotic** [comment]
Great, @pdurbin! I've started a  bit of editing on your chapter and will get you more feedback over the next day or two. Would you mind granting me "Editing" permissions rather than "Suggesting" powers? Working with the latter already has the draft looking like a pile of green spaghetti and makes re-reading quite difficult.

**Comment by pdurbin** [comment]
@semioticrobotic thanks for taking a look! Yes, I agree that this now looks like spaghetti:

![screen shot 2017-09-25 at 11 01 23 am](https://user-images.githubusercontent.com/21006/30815362-f733279c-a1e0-11e7-942d-7c516ec57c93.png)

I'm sure you have good feedback in there but no, I'm not going to grant you edit permissions. When I was an English tutor in college I didn't change anything they wrote, though many of them would have liked me to! We had a conversation. Can you please switch to using the "comments" feature to say why you do or don't like something? Thanks!

Please be advised that my lovely wife gave me feedback and I'll be rewriting a bit here and there. Please don't be offended if I don't incorporate all of your suggestions. I'll be quite happy to have eye on typos and punctuation especially one I've nailed down a couple sections better. Thanks again!

**Comment by semioticrobotic** [comment]
Roger that, @pdurbin. No offense taken. I'll get back to work.

**Comment by pdurbin** [comment]
@semioticrobotic ok, I'm ready for more feedback now. One of the main things I changed was reworking the contributing and challenges sections. Thanks!

**Comment by semioticrobotic** [comment]
Looking good, @pdurbin. I just took another pass. It's really shaping up.

Most pressing now are the final two sections of the chapter: the one explaining your challenges and the one outlining the benefits you've seen. Adding more detail, additional examples, or more color to those would be really helpful! Don't worry about chapter length; the quality of the story is what matters most.

**Comment by pdurbin** [comment]
@semioticrobotic thanks, I'll see what I can do. I did make a few revisions. I'm flying out to give my talk. I hope we can pick this up when I get back into the office on Tuesday, Oct. 10th. Please feel free to keep making comments!

**Comment by semioticrobotic** [comment]
Great, @pdurbin. I'll have a look. In the meantime: Travel safely, and we'll return to this when you're settled.

**Comment by pdurbin** [comment]
@semioticrobotic I'm back. What do you want from me when?

**Comment by semioticrobotic** [comment]
Cool! Welcome back, @pdurbin. Your chapter is in good shape, going from strength to strength. Those last two sections could use additional elaboration and detail (see my notes in the document). Is that something you're able to provide?

**Comment by pdurbin** [comment]
@semioticrobotic thanks. Today I made quite a few edits. You're welcome to check out the latest: https://docs.google.com/document/d/1ZbkHtHe19xadLFZoWnVxbS0XFzau2OGbDGwGaKGYqfE/edit?usp=sharing

**Comment by semioticrobotic** [comment]
Really great revision, @pdurbin. As you can see in your document, I had very little to add or change. How are you feeling about it? Want to get it into typesetting and pre-publication?

**Comment by pdurbin** [comment]
@semioticrobotic thanks. I'll give my case study at least one more read through but I'm glad you're happy with it.

I just finished reading [The Open Organization](https://www.redhat.com/en/explore/the-open-organization-book), by the way, and really enjoyed it.

**Comment by semioticrobotic** [comment]
Great to hear, @pdurbin. Always happy to publish more of your thinking on issues like these. I will begin the final prep work on your chapter and be in touch soon.

**Comment by pdurbin** [comment]
@semioticrobotic oh, I thought I'd have a little more time to give it one more read through, which I'm doing now.

**Comment by pdurbin** [comment]
@semioticrobotic ok, I made a few tweaks. What's next? Thanks!

**Comment by semioticrobotic** [comment]
No sweat! Sorry for this misunderstanding. I'll be sure to use the current version as the "final" version and get you a link for review soon.

**Comment by semioticrobotic** [comment]
Do you have an account on Opensource.com, @pdurbin? If so, what's your user name?

**Comment by pdurbin** [comment]
@semioticrobotic great and no worries. I just created an account with the username "pdurbin": https://opensource.com/users/pdurbin

**Comment by semioticrobotic** [comment]
Thanks!

**Comment by semioticrobotic** [comment]
[Check this out](https://opensource.com/open-organization/17/11/transparency-dataverse-project), @pdurbin. let me know if you have any final changes or suggestions (note, though, that headlines are still in flux as our editorial team refines them). When you finish setting up your account, your picture and bio will automatically appear.

**Comment by pdurbin** [comment]
@semioticrobotic it looks fine to me but I'm sending it out to four people for a final review. How much time to they have?

**Comment by semioticrobotic** [comment]
We'll need your final input by next Tuesday, @pdurbin. Bear in mind that the pre-publication link you have is only accessible to you, so you'll need to send PDFs or screengrabs of the article to your readers.

**Comment by pdurbin** [comment]
@semioticrobotic ok, thanks. Yes, I sent PDFs around. Is it expected that I am unable to edit the version at https://opensource.com/open-organization/17/11/transparency-dataverse-project ? This is what I see:

<img width="494" alt="screen shot 2017-10-27 at 7 48 57 am" src="https://user-images.githubusercontent.com/21006/32102665-5ab1e222-baeb-11e7-8927-96722686864b.png">


Some feedback is already coming in and I'd like to change...

"Lately the Dataverse project has been settling on a compromise where unpolished designs are public on a separate kanban board but not announced."

to

"Lately the Dataverse project has been posting unpolished designs on a separate kanban board that is public but not announced."

**Comment by semioticrobotic** [comment]
Sorry about that, @pdurbin. You should have proper editorial privileges now.

**Comment by pdurbin** [comment]
@semioticrobotic thanks! I fixed that line about unpolished designs.

**Comment by semioticrobotic** [comment]
Are we ready to rock, @pdurbin? Should get this into production for Thursday.

**Comment by pdurbin** [comment]
Punch it, Chewie!

![ani-falcon_jumps_to_lightspeed](https://user-images.githubusercontent.com/21006/32253344-c4b754b2-be70-11e7-896b-3ca04463e056.gif)
