### ISSUE TITLE
Intro for Inclusivity Unit

### ISSUE THREAD

**Issue by flaper87** [open-organization-ambassadors/open-org-workbook#8]
I'd like to contribute a chapter on the importance and effectiveness of different cultures in an open/any organization. The chapter would elaborate on some common cultural behaviors seen in organizations, how different cultures interact with each other, and why they are relevant for the organization.

Diversity goes beyond gender and race. It includes cultures, timezones, and a span of other variants that have direct impact on how tasks are executed.

I've written about this in the past. There are link to external resources in each of the posts. I'd love to expand this content further.

- http://blog.flaper87.com/on-communities-empower-humans-to-be-amazing.html#one
- http://blog.flaper87.com/on-communities-evaluating-your-own-values.html#one
- http://blog.flaper87.com/on-communities-when-should-change-happen.html#one

**Comment by semioticrobotic** [comment]
Thanks, @flaper87! Your writing would really lend itself well to the introductory sections of either the **Inclusivity** or **Community** sections. Are you interested in working on one of those?

**Comment by flaper87** [comment]
@semioticrobotic yup, I'd love to help with either.

Looking forward to collaborating to this. Please, lemme know how to proceed and any important deadline :)

**Comment by semioticrobotic** [comment]
That's great to hear, @flaper87. You can see the entire project timeline [in the README](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/README.md). Introductions will likely take a bit longer to write because they might include specific references to the case studies and exercises that are appearing in the sections they're introducing! But in the meantime, if you'd like to get started with brainstorming or even some high-level writing, feel free to reach out, drop me a line, share a working doc, etc.

**Comment by flaper87** [comment]
@semioticrobotic roger that! Will do.

Just another reference of what I'd be writing about (this post **just** went live): http://superuser.openstack.org/articles/navigate-cultures-open-source/

**Comment by semioticrobotic** [comment]
Great job, @flaper87! Looking forward to working with you.

**Comment by semioticrobotic** [comment]
We've crossed our [first milestone](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/README.md), @flaper87! That means we're now moving onto the writing stage of the project. Please feel free to drop me a line (here, email—whatever works) with your questions, comments, and concerns as you go along. You can also send a note to <bbehrens@redhat.com> if you'd like me to add you to the author email list.

Have fun with the introduction!

**Comment by flaper87** [comment]
@semioticrobotic hi :D I've shared a gdoc with you with the first draft :D

**Comment by semioticrobotic** [comment]
So I see! Thank you. It's at the top of my list of items to review this morning.

**Comment by semioticrobotic** [comment]
It's a great first draft, @flaper87! Thanks for taking it on. I have made some suggestions for you in the document. See what you think, and we'll work our way through.

**Comment by semioticrobotic** [comment]
This chapter is complete and has been typeset. Nice job, @flaper87!
