### ISSUE TITLE
Intro for Community Unit

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization-ambassadors/open-org-workbook#9]
Hi everyone,
I would like to propose the introduction to the Community chapter. 
My draft at what it might look like is based on the idea that it should give a high-level overview of communities, and specifically open source communities, their pros and cons, and briefly highlight how the case studies describe how the use of open communities changed the culture, collaboration, peformance, etc of the organization, or of their work. 

Thank you in advance for your feedback . 

(Note: I will also  be proposing the intro to the Collaboration chapter as well - not sure what everyone thinks of either proposal so I thought I would toss my ideas out there and let the community decide if they like either idea.) 

Best wishes, 
Heidi 

---------------------------------------------------------------
[Added 8/16/2017 by HeidiHVL] What are communities? 
Communities are social networks with shared values, activities, beliefs, and goals. They can be face-to-face, like traditional religious communities, political communities, or geographic communities or, using modern technology, they can be virtual. [Add more here...purpose, etc] 

Community influence 
Communities are influencers and are influenced by their members. 
They are part of a system of activity which engages and influences their members and yet they are influenced by their members as well. 

Benefits and disadvantages of communities 
Communities are social networks that provide support, enlarge networks (e.g. weak and strong ties), disseminate information, provide education and mentorship, define modes of behavior, beliefs and roles.  

Communities have drawbacks too - the very advantages can also become disadvantages, for instance propagating entrenched knowledge or creating knowledge that is too prescriptive; creating patterns of behaviour and sets of values that don't adapt to the dynamic external context or culture; limiting access to community decisions by  In other words, communities can frame our ways of thinking and being and become "The Box" we are later encouraged to think outside of! 

Open Source Communities 
(Note: Open Source community research goes here that would level-set our understanding and expectations. Eg. Specifically, what is their history? what are their shared values? )

Ultimately Open Source communities have emerged as a new way for people to contribute, and are particularly relevant to solving difficult problems and economic situations. 

(Note: Maybe here is where to tie in the general ideas from the case studies. Case 1 descibes this, Case 2 describes that, etc) 

Since all communities have the power to be harmful to those they serve, or beneficial to those they serve, we need to ask ourselves what would make Open Communities thrive where others have failed? The other qualities of Transparency, Inclusivity, Adaptabiliy, and Collaboration, give open communities the potential to self-regulate and self-heal . Other types of communities, often founded on the command-and-control paradigms, frequently struggle with change and wind up being archaic and limiting when their surrounding culture and context change 

But the self-healing potential of open communities is just that: a potential. As always it is up to the people to enact this potential.

**Comment by semioticrobotic** [comment]
I really like this outline, @HeidiHVL. One important point not to skip: an answer to the question_What is "community"?_In other words, before discussing open source communities, the benefits and drawbacks of communities, etc., be sure your readers get a clear sense of what, precisely, we mean by "community" in the first place. This book is for absolute beginners; don't be afraid to spell this out and be very deliberate about it.

**Comment by semioticrobotic** [comment]
I want to add, too, that I really appreciate the way that you drew the other four open organization principles into your discussion. Great move there.

**Comment by HeidiHVL** [comment]
@semioticrobotic  thanks for the feedback. I also appreciate you letting me know about the audience. I wasn't sure if I needed to cover "what are communities?", which I can certainly do.

**Comment by semioticrobotic** [comment]
Yes, please! As basic and straightforward as possible. Beginning the writing with a sentence that begins "Community is ..." would not be at all inappropriate.
